name: Sample Jekyll Blog
description: This is a sample Jekyll Blog.
author: Weichao Qiu
author_email: qiuwch@gmail.com
category_dir: /
baseurl:
url: http://jhu-vr.github.io/

# markdown: rdiscount
permalink: pretty
paginate: 3
# exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
